### ISSUE TITLE
Issue Accessing Website in VM

### ISSUE THREAD

**Issue by ARule** [cmacdonell/UshahidiVM#2]
Following steps 1-14, I have successfully set up the Ushahidi VM. After trying step 15, accessing the website using "localhost:3000" does not work. It gives the following error: _Sorry, something went wrong. Try reloading the page._ I searched just localhost to make sure that it was responsive and have attached the screenshots from the Raw data and Headers
<img width="675" alt="localhost-headers" src="https://user-images.githubusercontent.com/25963910/46891200-196e9200-ce37-11e8-88aa-aaedd702c43c.png">
<img width="705" alt="localhost-rawdata" src="https://user-images.githubusercontent.com/25963910/46891201-196e9200-ce37-11e8-9f54-007c82d33f70.png">

I also tried accessing the website through the host machine using the IP address, but that didn't work either. I know that it is not a network connection problem because I could reach outside sites like CNN. I've double checked the instructions and am not sure what the problem is. It might be the Ushahidi website itself? Thanks!

**Comment by cmacdonell** [comment]
Hi,

When you open http://localhost:3000 in the browser and see "Sorry, something went wrong", can you paste here what the console says? You would access the console via the Developer Tools.

**Comment by ARule** [comment]
<img width="1280" alt="console" src="https://user-images.githubusercontent.com/25963910/47112991-d9882000-d225-11e8-8099-6c2305eadf54.png">

**Comment by cmacdonell** [comment]
Ah, OK.  In the `platform-client` directory, what is the content of the `.env` file? Particularly, there should be an entry for BACKEND_URL.

**Comment by cmacdonell** [comment]
Setting the BACKEND_URL  to the internal IP address fixed this issue.
